// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcvlxtkxqyaznxxvkynd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjdmx4dGt4cXlhem54eHZreW5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MTAzMzYsImV4cCI6MjA2MzI4NjMzNn0.Wuj5cEFNHLzBUUU_WVFBkWvPmf3-0_zNGDHCwoLEnMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);